#!/bin/sh

chmod +x /usr/share/arewegreen/*.jar

ln -fs /usr/share/arewegreen/arewegreen.jar /etc/init.d/arewegreen

update-rc.d arewegreen defaults
service arewegreen start

echo "arewegreen was successfully installed. Open http://localhost:8089 to see your dashboard."