#!/bin/sh

# make sure it's dead
service arewegreen stop
killall -9 -u arewegreen &> /dev/null || /bin/true

# rm init script stuff
update-rc.d arewegreen remove
rm -f /etc/init.d/arewegreen

# rm logs
rm -f /var/log/arewegreen.log

# rm system user
deluser --system arewegreen
